apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2-container
        image: watri/service2:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 20m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /service2
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /service2
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: service2-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30003

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service2-hpa
  namespace: prod
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service2-deployment
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 0
  desiredReplicas: 0

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service2-ingress
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: demo.127.0.0.1.nip.io
      http:
        paths:
          - path: /service2
            pathType: Prefix
            backend:
              service:
                name: service2-service
                port:
                  number: 3000
