apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1-container
        image: watri/service1:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 20m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /service1
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /service1
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: service1-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service1-hpa
  namespace: prod
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service1-deployment
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 0
  desiredReplicas: 0

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service1-ingress
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: demo.127.0.0.1.nip.io
      http:
        paths:
          - path: /service1
            pathType: Prefix
            backend:
              service:
                name: service1-service
                port:
                  number: 8080